### ISSUE TITLE
Fix: Remove Username from User model.

### ISSUE THREAD

**Issue by Sonictherocketman** [TorkamaniLab/gene-pc-api#11]
We aren't going to be asking them for usernames and we can basically just ask for their email if we need to send them anything. The trial data is constrained to their device.

**Comment by bmolparia** [comment]
Do you mean user_id? Because we need that.

**Comment by Sonictherocketman** [comment]
[This](https://github.com/TorkamaniLab/gene-pc-api/blob/master/gene_pc_api/gene_pc_api/serializers.py#L27)
